name: Tests

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - name: PHPUnit
      uses: php-actions/phpunit@v1
      with:
        config: ./phpunit.xml.dist
    - name: PHP CS Fixer
      uses: StephaneBour/actions-php-cs-fixer@1.0
      with:
        dir: './src'
